global:
  baseNamespace: microservice
  dockerRegistryUrl: localhost:5000
  hostName: microservice-host
name: customer-service
replicaCount: 1
port: 8080
image:
  repository: customer-service
username: user
password: password
role: ACTUATOR
discoveryEnabled: true

resources:
  memory: 512Mi
  java:
    opts: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=70.0 -XX:+ExitOnOutOfMemoryError"
actuator:
  showValues: ALWAYS
  path: /actuator
server:
  path: /
logstash:
  location: logstash.infra:5044
zipkin:
  enabled: true
  url: zipkin.infra
  port: 9411
sleuth:
  enabled: true
  messaging:
    enabled: true
rabbit:
  host: rabbit.infra
  port: 5672
  username: user
  password: password
prometheus:
  scrape: true
feign:
  account:
    serviceName: account-service
    port: 8080
profile: stdout